apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "autopep8"
  namespace: "venky-backend"
  labels:
    app: "backend"
spec:
  replicas: 10 #(origina+copy)
  selector:
    matchLabels:
      app: "backend"
  template:
    metadata:
      labels:
        app: "backend"
    spec:
      containers:
        - name: "autopep8"
          image: "888576196681.dkr.ecr.us-east-1.amazonaws.com/kubernetes-project:tag"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"

              cpu: "500m"

