apiVersion: "v1"
kind: "Service"
metadata:
  name: "autopep8"
  namespace: "venky-backend"
  labels:
    app: "backend"
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 4000
  selector:
    app: "k8s-node"
  type: "LoadBalancer"